service: rs-cart-api-kr1-nestjs-app
frameworkVersion: '3'
plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-1
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
functions:
  app:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          path: '/{proxy+}'
          method: 'ANY'
          cors: true
